name: cash_on_hand
description: "Smart savings tracker with goal-based financial planning and year-end targets."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.1+15

environment:
  sdk: ^3.5.2

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.2
  table_calendar: ^3.1.2
  uuid: ^3.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  drift: ^2.28.0
  path_provider: ^2.1.5
  path: ^1.8.3
  get_it: ^7.6.7
  injectable: ^2.3.2
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  lottie: ^3.3.2
  confetti: ^0.7.0
  share_plus: ^12.0.1
  decimal: ^3.0.1
  fl_chart: ^0.69.0
  sqlite3_flutter_libs: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.28.0
  injectable_generator: ^2.4.1
  test: ^1.24.9
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_intl:
  enabled: true
  arb_dir: lib/localization
  output_dir: lib/generated


