import 'package:freezed_annotation/freezed_annotation.dart';

part 'financial_suggestion.freezed.dart';
part 'financial_suggestion.g.dart';

/// Types of financial suggestions
enum SuggestionType {
  savingsOpportunity,
  budgetWarning,
  goalRecommendation,
  spendingPattern,
  roundUpOptimization,
  allocationImprovement,
  goalMilestone,
  unusualActivity,
}

/// Priority levels for suggestions
enum SuggestionPriority {
  low,
  medium,
  high,
  urgent,
}

/// A financial suggestion or insight generated by the AI engine
@freezed
class FinancialSuggestion with _$FinancialSuggestion {
  const factory FinancialSuggestion({
    required String id,
    required SuggestionType type,
    required SuggestionPriority priority,
    required String title,
    required String description,
    String? actionText,
    String? actionRoute,
    Map<String, dynamic>? actionData,
    double? potentialSavings,
    int? relatedGoalId,
    int? relatedCategoryId,
    required DateTime createdAt,
    DateTime? expiresAt,
    @Default(false) bool isDismissed,
    @Default(false) bool isActionTaken,
    DateTime? dismissedAt,
    DateTime? actionTakenAt,
  }) = _FinancialSuggestion;

  const FinancialSuggestion._();

  factory FinancialSuggestion.fromJson(Map<String, dynamic> json) =>
      _$FinancialSuggestionFromJson(json);

  /// Check if suggestion is still active
  bool get isActive {
    if (isDismissed || isActionTaken) return false;
    if (expiresAt != null && DateTime.now().isAfter(expiresAt!)) return false;
    return true;
  }

  /// Get icon for suggestion type
  String get iconName {
    switch (type) {
      case SuggestionType.savingsOpportunity:
        return 'savings';
      case SuggestionType.budgetWarning:
        return 'warning';
      case SuggestionType.goalRecommendation:
        return 'flag';
      case SuggestionType.spendingPattern:
        return 'analytics';
      case SuggestionType.roundUpOptimization:
        return 'trending_up';
      case SuggestionType.allocationImprovement:
        return 'auto_awesome';
      case SuggestionType.goalMilestone:
        return 'celebration';
      case SuggestionType.unusualActivity:
        return 'notification_important';
    }
  }

  /// Get color for suggestion priority
  String get priorityColor {
    switch (priority) {
      case SuggestionPriority.low:
        return 'grey';
      case SuggestionPriority.medium:
        return 'blue';
      case SuggestionPriority.high:
        return 'orange';
      case SuggestionPriority.urgent:
        return 'red';
    }
  }

  /// Get display text for suggestion type
  String get typeDisplayName {
    switch (type) {
      case SuggestionType.savingsOpportunity:
        return 'Savings Opportunity';
      case SuggestionType.budgetWarning:
        return 'Budget Alert';
      case SuggestionType.goalRecommendation:
        return 'Goal Recommendation';
      case SuggestionType.spendingPattern:
        return 'Spending Insight';
      case SuggestionType.roundUpOptimization:
        return 'Round-Up Tip';
      case SuggestionType.allocationImprovement:
        return 'Allocation Insight';
      case SuggestionType.goalMilestone:
        return 'Goal Milestone';
      case SuggestionType.unusualActivity:
        return 'Activity Alert';
    }
  }
}

/// User spending patterns and analytics
@freezed
class SpendingPattern with _$SpendingPattern {
  const factory SpendingPattern({
    required int categoryId,
    required String categoryName,
    required double averageMonthly,
    required double currentMonth,
    required double lastMonth,
    required int transactionCount,
    required DateTime firstTransaction,
    required DateTime lastTransaction,
    required List<double> monthlyTrends,
    double? peakAmount,
    DateTime? peakDate,
    @Default([]) List<String> frequentMerchants,
  }) = _SpendingPattern;

  const SpendingPattern._();

  factory SpendingPattern.fromJson(Map<String, dynamic> json) =>
      _$SpendingPatternFromJson(json);

  /// Calculate spending trend (positive = increasing, negative = decreasing)
  double get trendPercentage {
    if (lastMonth == 0) return currentMonth > 0 ? 100 : 0;
    return ((currentMonth - lastMonth) / lastMonth) * 100;
  }

  /// Check if spending is increasing significantly
  bool get isIncreasingTrend => trendPercentage > 20;

  /// Check if spending is decreasing significantly  
  bool get isDecreasingTrend => trendPercentage < -20;

  /// Calculate variance from average
  double get varianceFromAverage {
    if (averageMonthly == 0) return currentMonth > 0 ? 100 : 0;
    return ((currentMonth - averageMonthly) / averageMonthly) * 100;
  }

  /// Check if current spending is unusually high
  bool get isUnusuallyHigh => varianceFromAverage > 50;

  /// Check if current spending is unusually low
  bool get isUnusuallyLow => varianceFromAverage < -50;
}

/// Savings opportunity detection result
@freezed
class SavingsOpportunity with _$SavingsOpportunity {
  const factory SavingsOpportunity({
    required String id,
    required String title,
    required String description,
    required double potentialMonthlySavings,
    required double confidence, // 0.0 to 1.0
    required SuggestionType suggestionType,
    int? categoryId,
    int? goalId,
    Map<String, dynamic>? analysisData,
    required DateTime detectedAt,
  }) = _SavingsOpportunity;

  const SavingsOpportunity._();

  factory SavingsOpportunity.fromJson(Map<String, dynamic> json) =>
      _$SavingsOpportunityFromJson(json);

  /// Calculate potential annual savings
  double get potentialAnnualSavings => potentialMonthlySavings * 12;

  /// Get confidence level as text
  String get confidenceLevel {
    if (confidence >= 0.8) return 'High';
    if (confidence >= 0.6) return 'Medium';
    if (confidence >= 0.4) return 'Low';
    return 'Very Low';
  }

  /// Check if opportunity is worth suggesting
  bool get isWorthSuggesting => 
      potentialMonthlySavings >= 5.0 && confidence >= 0.4;
}

/// Goal progress insights and notifications
@freezed
class GoalInsight with _$GoalInsight {
  const factory GoalInsight({
    required int goalId,
    required String goalTitle,
    required double currentAmount,
    required double targetAmount,
    required DateTime targetDate,
    required double monthlyRequired,
    required double averageMonthlyContribution,
    required int daysRemaining,
    required bool isOnTrack,
    double? projectedShortfall,
    DateTime? projectedCompletionDate,
    @Default([]) List<String> recommendations,
  }) = _GoalInsight;

  const GoalInsight._();

  factory GoalInsight.fromJson(Map<String, dynamic> json) =>
      _$GoalInsightFromJson(json);

  /// Calculate progress percentage
  double get progressPercentage => 
      targetAmount > 0 ? (currentAmount / targetAmount).clamp(0.0, 1.0) : 0.0;

  /// Calculate how much behind/ahead the user is
  double get monthlyGap => monthlyRequired - averageMonthlyContribution;

  /// Check if goal is at risk
  bool get isAtRisk => !isOnTrack && daysRemaining < 90;

  /// Check if goal is likely to be completed early
  bool get isAheadOfSchedule => 
      projectedCompletionDate != null && 
      projectedCompletionDate!.isBefore(targetDate);

  /// Get status message
  String get statusMessage {
    if (isAheadOfSchedule) {
      return 'Ahead of schedule!';
    } else if (isOnTrack) {
      return 'On track';
    } else if (isAtRisk) {
      return 'At risk';
    } else {
      return 'Behind schedule';
    }
  }
}