// Mocks generated by Mockito 5.4.4 from annotations
// in cash_on_hand/test/services/event_service_first_occurrence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cash_on_hand/core/error/failures.dart' as _i5;
import 'package:cash_on_hand/data/models/enums/delete_option.dart' as _i7;
import 'package:cash_on_hand/data/models/freezed/event.dart' as _i6;
import 'package:cash_on_hand/data/repositories/i_event_repository.dart' as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IEventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIEventRepository extends _i1.Mock implements _i3.IEventRepository {
  MockIEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>> getEvents(
          DateTime? day) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [day],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Event>>(
          this,
          Invocation.method(
            #getEvents,
            [day],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>> getEventsForRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsForRange,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Event>>(
          this,
          Invocation.method(
            #getEventsForRange,
            [
              start,
              end,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>> getAllEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Event>>(
          this,
          Invocation.method(
            #getAllEvents,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Event>> addEvent(
    DateTime? day,
    _i6.Event? event,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [
            day,
            event,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Event>>.value(
            _FakeEither_0<_i5.Failure, _i6.Event>(
          this,
          Invocation.method(
            #addEvent,
            [
              day,
              event,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Event>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>> addRecurringEvent(
    DateTime? startDay,
    _i6.Event? event,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecurringEvent,
          [
            startDay,
            event,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Event>>(
          this,
          Invocation.method(
            #addRecurringEvent,
            [
              startDay,
              event,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Event>> updateEvent(
    DateTime? day,
    _i6.Event? oldEvent,
    _i6.Event? newEvent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [
            day,
            oldEvent,
            newEvent,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Event>>.value(
            _FakeEither_0<_i5.Failure, _i6.Event>(
          this,
          Invocation.method(
            #updateEvent,
            [
              day,
              oldEvent,
              newEvent,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Event>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteEvent(
    DateTime? day,
    _i6.Event? event,
    _i7.DeleteOption? option,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [
            day,
            event,
            option,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteEvent,
            [
              day,
              event,
              option,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteEventSeries(
          _i6.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEventSeries,
          [event],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteEventSeries,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> hasEvents(DateTime? day) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasEvents,
          [day],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #hasEvents,
            [day],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTotalEvents() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalEvents,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #getTotalEvents,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>> getEventSeries(
          int? originalEventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventSeries,
          [originalEventId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Event>>(
          this,
          Invocation.method(
            #getEventSeries,
            [originalEventId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Event>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, T>> catchError<T>(
          _i4.Future<T> Function()? call) =>
      (super.noSuchMethod(
        Invocation.method(
          #catchError,
          [call],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, T>>.value(
            _FakeEither_0<_i5.Failure, T>(
          this,
          Invocation.method(
            #catchError,
            [call],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, T>>);
}
